baseURL = 'https://dragos.se/'
title = 'DragosLarm AB'

defaultContentLanguage = 'sv'

[languages]
  [languages.de]
    contentDir = 'content/de'
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 3
    [languages.de.params]
      flag = '🇩🇪'
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [languages.en.params]
      flag = '🇺🇸'
  [languages.sv]
    contentDir = 'content/sv'
    languageCode = 'sv-SE'
    languageDirection = 'ltr'
    languageName = 'Svenska'
    weight = 1
    [languages.sv.params]
      flag = '🇸🇪'
