[[main]]
name = 'Heim'
pageRef = '/'
weight = 10

[[main]]
name = 'Produkte'
pageRef = 'products'
weight = 20

[[main]]
name = 'Anwendungsbereiche'
pageRef = 'applications'
weight = 30

[[main]]
name = 'Über uns'
pageRef = 'about'
weight = 40
